services:
  apt-cacher-ng:
    restart: always
    image: docker.io/prplanit/apt-cacher-ng-oci:latest
    ports:
      - "3142:3142"
    volumes:
      - /srv/apt-cacher-ng/cache:/var/cache/apt-cacher-ng
      - /srv/apt-cacher-ng/log:/var/log/apt-cacher-ng
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
    security_opt:
      - no-new-privileges:true
