apiVersion: v1
kind: Pod
metadata:
  name: apt-cacher-ng
  labels:
    app: apt-cacher-ng
spec:
  containers:
    - name: apt-cacher-ng
      image: docker.io/prplanit/apt-cacher-ng-oci:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "64Mi"
          cpu: "500m"
      ports:
        - containerPort: 3142
          protocol: TCP
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ALL]
          add: [CHOWN, SETUID, SETGID, DAC_OVERRIDE]
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - mountPath: /var/cache/apt-cacher-ng
          name: cache
        - mountPath: /var/log/apt-cacher-ng
          name: log
        - mountPath: /run/apt-cacher-ng
          name: run
  volumes:
    - name: cache
      emptyDir: {}
    - name: log
      emptyDir: {}
    - name: run
      emptyDir: {}
